added: rsvp events and api, fixed: missing calendar properties
zaida04/guilded.js pull request #169
Opened 2022-08-21 04:54 UTC by AusKarlos87

Please describe the changes this PR makes and why it should be merged:
Added all rsvp websocket events and methods associated with creating/updating and deleting rsvps via the bot API.
Rsvps are cached (if enabled) in a collection with their associated cached calendar event

Status

-   [x] Code changes have been tested.

Semantic versioning classification:

-   [x] This PR changes the library's interface (methods or parameters added)
-   [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
-   [ ] This PR only includes non-code changes, like changes to documentation, README, etc.

2022-08-23 16:33 UTC, zaida04 requested changes

2022-08-23 16:33 UTC, zaida04 commented on packages/guilded.js/lib/gateway/ClientGatewayHandler.ts
> +    CalendarEventRsvpHandler = new CalendarEventRsvpHandler(this.client);
```suggestion
    calendarEventRsvpHandler = new CalendarEventRsvpHandler(this.client);
```

2022-08-23 16:33 UTC, zaida04 commented on packages/guilded.js/lib/gateway/ClientGatewayHandler.ts
> +        [WebSocketEvents.CalendarEventRsvpDeleted]: (data) => this.CalendarEventRsvpHandler.calendarEventRsvpDeleted(data as WSCalendarEventRsvpDeleted),
```suggestion
        [WebSocketEvents.CalendarEventRsvpUpdated]: (data) => this.calendarEventRsvpHandler.calendarEventRsvpUpdated(data as WSCalendarEventRsvpUpdated),
        [WebSocketEvents.CalendarEventRsvpManyUpdated]: (data) => this.calendarEventRsvpHandler.calendarEventRsvpManyUpdated(data as WSCalendarEventRsvpManyUpdated),
        [WebSocketEvents.CalendarEventRsvpDeleted]: (data) => this.calendarEventRsvpHandler.calendarEventRsvpDeleted(data as WSCalendarEventRsvpDeleted),
```

2022-08-23 16:33 UTC, zaida04 commented on packages/rest/lib/util/Router.ts
> +        return this.rest.put<RESTPatchCalendarEventRsvpResult>(ROUTES.calendarEventRsvp(channelId, calendarEventId, userId), options);
```suggestion
        return this.rest.put<RESTPatchCalendarEventRsvpResult, RESTPatchCalendarEventRsvpBody>(ROUTES.calendarEventRsvp(channelId, calendarEventId, userId), options);
```

2022-08-24 17:24 UTC, zaida04 approved these changes

2022-08-24 17:26 UTC, zaida04 commented
once you review, feel free to merge @DaStormer

2022-08-24 22:08 UTC, DaStormer approved these changes

2022-08-24 22:09 UTC, merged