feat: forum topics
zaida04/guilded.js pull request #171
Opened 2022-09-09 15:50 UTC by zaida04

Please describe the changes this PR makes and why it should be merged:

Status

-   [ ] Code changes have been tested.

Semantic versioning classification:

-   [ ] This PR changes the library's interface (methods or parameters added)
-   [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
-   [ ] This PR only includes non-code changes, like changes to documentation, README, etc.

2022-09-09 16:04 UTC, Uhuh approved these changes

2022-09-10 18:54 UTC, DaStormer requested changes

2022-09-10 18:54 UTC, DaStormer commented on packages/guilded-api-typings/lib/v1/structs/Forum.ts
> +    mentions: MentionsPayload;
```suggestion
    updatedAt?: string;
    /** When, if at all, this forum topic was bumped */
    bumpedAt?: string;
    /** Whether this forum topic is pinned */
    isPinned?: boolean;
    /** The mentions within this forum topic */
    mentions?: MentionsPayload;
```

2022-09-10 18:54 UTC, DaStormer commented on packages/guilded.js/lib/gateway/ClientGatewayHandler.ts
> +            this.forumHandler.ForumTopicUnpinned(data as WSForumTopicUnpinned)
```suggestion
        [WebSocketEvents.ForumTopicCreated]: (data) => 
            this.forumHandler.forumTopicCreated(data as WSForumTopicCreated),
        [WebSocketEvents.ForumTopicDeleted]: (data) => 
            this.forumHandler.forumTopicDeleted(data as WSForumTopicDeleted),
        [WebSocketEvents.ForumTopicUpdated]: (data) => 
            this.forumHandler.forumTopicUpdated(data as WSForumTopicUpdated),
        [WebSocketEvents.ForumTopicPinned]: (data) => 
            this.forumHandler.forumTopicPinned(data as WSForumTopicPinned),
        [WebSocketEvents.ForumTopicUnpinned]: (data) =>
            this.forumHandler.forumTopicUnpinned(data as WSForumTopicUnpinned)
```

2022-09-10 18:54 UTC, DaStormer commented on packages/guilded.js/lib/gateway/handler/ForumEventHandler.ts
> +    ForumTopicCreated(data: WSForumTopicCreated) {
```suggestion
    forumTopicCreated(data: WSForumTopicCreated) {
```

2022-09-10 18:54 UTC, DaStormer commented on packages/guilded.js/lib/gateway/handler/ForumEventHandler.ts
> +    ForumTopicUpdated(data: WSForumTopicUpdated) {
```suggestion
    forumTopicUpdated(data: WSForumTopicUpdated) {
```

2022-09-10 18:54 UTC, DaStormer commented on packages/guilded.js/lib/gateway/handler/ForumEventHandler.ts
> +    ForumTopicDeleted(data: WSForumTopicDeleted) {
```suggestion
    forumTopicDeleted(data: WSForumTopicDeleted) {
```

2022-09-10 18:54 UTC, DaStormer commented on packages/guilded.js/lib/gateway/handler/ForumEventHandler.ts
> +    ForumTopicPinned(data: WSForumTopicPinned) {
```suggestion
    forumTopicPinned(data: WSForumTopicPinned) {
```

2022-09-10 18:54 UTC, DaStormer commented on packages/guilded.js/lib/gateway/handler/ForumEventHandler.ts
> +    ForumTopicUnpinned(data: WSForumTopicUnpinned) {
```suggestion
    forumTopicUnpinned(data: WSForumTopicUnpinned) {
```

2022-09-10 18:54 UTC, DaStormer commented on packages/guilded.js/lib/gateway/handler/MessageEventHandler.ts
> +        if(this.client.messages.shouldCacheMessage) this.client.messages.cache.set(newMessage.id, newMessage);
```suggestion
        if (this.client.messages.shouldCacheMessage) this.client.messages.cache.set(newMessage.id, newMessage);
```

2022-09-10 18:54 UTC, DaStormer commented on packages/guilded.js/lib/managers/global/ForumManager.ts
> +        return this.client.rest.router.deleteForumTpoic(channelId, forumThreadId);
```suggestion
        return this.client.rest.router.deleteForumTopic(channelId, forumThreadId);
```

2022-09-10 18:54 UTC, DaStormer commented on packages/rest/lib/util/Router.ts
> +    deleteForumTpoic(channelId: string, forumThreadId: string): Promise<RESTDeleteForumTopicResult> {
```suggestion
    deleteForumTopic(channelId: string, forumThreadId: string): Promise<RESTDeleteForumTopicResult> {
```

2022-09-12 19:08 UTC, DaStormer approved these changes

2022-09-12 19:09 UTC, merged