gil: Implement Tasks Feature
zaida04/guilded.js pull request #89
Opened 2022-04-28 01:31 UTC by Skillz4Killz

Please describe the changes this PR makes and why it should be merged:

- Schedule tasks to run at certain times. Very basic needs for 99% of bots. If something more is needed for the rare edge case user, just customize and setup as needed.

Status

-   [ ] Code changes have been tested.

Semantic versioning classification:

-   [ ] This PR changes the library's interface (methods or parameters added)
-   [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
-   [ ] This PR only includes non-code changes, like changes to documentation, README, etc.

2022-04-28 02:34 UTC, DaStormer requested changes
Awesome feature! Just a few things I noticed

2022-04-28 02:34 UTC, DaStormer commented on packages/gil/lib/BotClient.ts
> +                try {
There's no check for requiring ready here

2022-04-28 02:34 UTC, DaStormer commented on packages/gil/lib/structures/Task.ts
> +    millisecondsInterval = 60 * 60 * 100;
```suggestion
    millisecondsInterval = 60 * 60 * 1000;
```

2022-04-28 02:34 UTC, DaStormer commented on packages/gil/lib/structures/Task.ts
> +    requireFullyReady = false;
I'm being a little picky here, but I feel like `requireFullyReady` is too verbose, can be simplified to `requireReady`

2022-04-28 17:22 UTC, zaida04 requested changes

2022-04-28 17:22 UTC, zaida04 commented on packages/gil/lib/BotClient.ts
>              setTimeout(async () => {
Could this not just be condensed into the setInterval call after the initial call in the lines above this?

2022-04-28 19:27 UTC, DaStormer approved these changes
other than nico's request, LGTM

2022-04-29 18:32 UTC, zaida04 approved these changes

2022-04-29 18:33 UTC, merged